// <auto-generated />
namespace UC.CSP.MeetingCenter.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStockOperations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStockOperations));
        
        string IMigrationMetadata.Id
        {
            get { return "201901012300587_AddStockOperations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
